name: Report a bug
description: Tell us about a bug or issue you may have identified.
title: "Create a report to help us improve"
labels: [bug]
assignees: "-"
body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: Take a couple minutes to help our maintainers work faster.
      options:
        - label: I have [searched](https://github.com/stacklok/minder/issues) for duplicate or closed issues
          required: true
        - label: I have read the [contributing guidelines](https://github.com/stacklok/minder/blob/main/CONTRIBUTING.md)
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the issue
      description: A clear and concise description of what the bug is. If applicable, add screenshots to illustrate the problem.
    validations:
      required: true
  - type: textarea
    id: reproduce-steps
    attributes:
      label: To Reproduce
      description: Describe the steps to reproduce the behavior.
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: What operating system(s) are you seeing the problem on?
      multiple: true
      options:
        - Windows
        - macOS
        - Android
        - iOS
        - Linux
  - type: dropdown
    id: browser
    attributes:
      label: What browser(s) are you seeing the problem on?
      multiple: true
      options:
        - Chrome
        - Safari
        - Firefox
        - Microsoft Edge
        - Opera
        - Brave
  - type: input
    id: version
    attributes:
      label: What version are you using?
      placeholder: "e.g., v5.1.0 or v4.5.2"
